TARGET_BOOTLOADER_BOARD_NAME := libra
TARGET_BOARD_INFO_FILE := $(DEVICE_PATH)/board-info.txt
TARGET_SYSTEM_PROP += $(DEVICE_PATH)/system.prop

TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true
